version: "3"

services:
  server:
    depends_on:
      - database
    build:
      dockerfile: Dockerfile
      context: ./backend/
    entrypoint: ["npm", "start"]
    ports:
      - "3000:3000"
    networks:
      - backend
    volumes:
      - ./backend/:/usr/src/app

  database:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - backend

networks:
  backend:
    name: backend_network